-   name: stop slapd
    service:
        name: slapd
        state: stopped

-   name: delete old dynamic configuration directory
    file:
        path: /usr/local/openldap/etc/openldap/slapd.d
        state: absent

-   name: create dynamic configuration directory
    file:
        path: /usr/local/openldap/etc/openldap/slapd.d
        state: directory
        owner: ldap
        group: ldap
        mode: 0770

-   name: copy ldif configuration
    copy:
        content: "{{openldap_config_ldif}}"
        dest: /usr/local/openldap/etc/openldap/openldap.ldif
        owner: ldap
        group: ldap
        mode: 0644

-   name: apply configuration
    shell: |
        /usr/local/openldap/sbin/slapadd \
            -F /usr/local/openldap/etc/openldap/slapd.d/ \
            -l /usr/local/openldap/etc/openldap/openldap.ldif \
            -n0 && \
        chown -R ldap:ldap /usr/local/openldap/etc/openldap/slapd.d
