-   name: LTB repository
    copy:
        content: |
            [ltb-project]
            name=LTB project packages
            baseurl=http://ltb-project.org/rpm/$releasever/$basearch
            enabled=1
            gpgcheck=1
            [ltb-project-srpms]
            name=LTB project packages
            baseurl=http://ltb-project.org/rpm/$releasever/SRPMS
            enabled=1
            gpgcheck=1
        dest: /etc/yum.repos.d/ltb-project.repo
-   name: LTB repository key
    rpm_key:
        state: present
        key: "https://ltb-project.org/wiki/lib/RPM-GPG-KEY-LTB-project"

-   name: install packages
    yum:
        name: openldap-ltb,openldap-ltb-contrib-overlays,openldap-ltb-mdb-utils
        state: installed
