-   include: "{{item}}"
    with_first_found:
    -   "install-{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    -   "install-{{ ansible_distribution }}-{{ ansible_distribution_version}}.yml"
    -   "install-{{ ansible_distribution }}.yml"

-   name: stop openldap
    service:
        name: slapd
        state: stopped
    when: openldap_initialize

-   name: delete openldap directories
    file:
        path: "{{item}}"
        state: absent
    with_items: "{{openldap_data_directories + [openldap_config_directory]}}"
    when: openldap_initialize

-   name: openldap directories
    file:
        path: "{{item}}"
        state: directory
        owner: ldap
        group: ldap
        mode: 0750
    with_items: "{{openldap_data_directories + [openldap_config_directory]}}"

-   name: configure /etc/default/slapd
    lineinfile:
        path: /etc/default/slapd
        line: "{{item.line}}"
        regexp: "{{item.regexp}}"
    with_items:
    -   line: 'SLAPD_SERVICES="{{openldap_slapd_services}}"'
        regexp: "^ *SLAPD_SERVICES"
    notify: restart openldap

-   name: test for openldap_apply_config_once_lockfile
    stat:
        path: openldap_apply_config_once_lockfile

-   include: config_ldif.yml
    when: |
        'openldap_config_ldif' in vars
        and not
        ( 
            openldap_apply_config_once
            and
            not openldap_apply_config_once_lockfile.stat.exists
        )

-   name: start slapd
    service:
        name: slapd
        state: started
    when: openldap_start
